#!/usr/bin/pythonb
from math import log
from math import ceil
from math import sin
from math import pi

amplitude = 4095 # peak value
table_size = 256


sine_num_bits = int(ceil(log(amplitude, 2)))

print "--- Quarter-Sine Wave Lookup Table"
print "--- values autogenerated with Python"
print "--- table values are magnitude * sin(table_index) from 0 to "

print "WIDTH={0};".format(sine_num_bits)
print "DEPTH={0};".format(table_size)
print "ADDRESS_RADIX=DEC"
print "DATA_RADIX=DEC"

print
print "CONTENT BEGIN"

for table_element in range(0,table_size):
    sine_val = int(amplitude * sin(table_element/float(table_size) * pi/2))
    print "{0}  :  {1};".format(table_element, sine_val)

print "END;"
